name:                vk-hear-bot
version:             0.1.0.0
github:              "typeundefined/vk-hear-bot"
license:             BSD3
author:              "Konstantin Nekrasov"
maintainer:          "const.nekrasoff@gmail.com"
copyright:           "Copyright (c) Konstantin Nekrasov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/typeundefined/vk-hear-bot#readme>

dependencies:
- base >= 4.7 && < 5
- req
- aeson
- configurator
- text
- bytestring
- mtl
- microlens
- microlens-th
- vector
- scientific

library:
  source-dirs: src

executables:
  vk-hear-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vk-hear-bot

tests:
  vk-hear-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vk-hear-bot
